export const ENDPOINT_API = {
	AUTH: 'auth',
	USER: 'user',
	CATEGORY: 'category',
	ATRIBUTE: 'atribute',
	TEMPLATE: 'template',
	SUPPLIER: 'supplier',
	BRAND: 'brand',
	PRODUCT: 'product',
	KARDEX: 'kardex',
	ESTABLISHMENT: 'establishment',
	CUSTOMER: 'customer',
	SALE: 'sale',
	BILLING: 'billing',
}
