import { UserRole } from '@/common/types/roles'
import { ALLOW_ROLES } from '@/common/constants/roles-const'

export const PERMISSIONS = {
	DASHBOARD: 'dashboard',
	CATEGORIES: 'categories',
	ATTRIBUTES: 'attributes',
	TEMPLATES: 'templates',
	PRODUCTS: 'products',
	SUPPLIERS: 'suppliers',
	SALES: 'sales',
	REPORTS: 'reports',
	USERS: 'users',
	CUSTOMERS: 'customers',
	ADMINISTRATION: 'administration',
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const ROLE_PERMISSIONS: Record<Permission, UserRole[]> = {
	[PERMISSIONS.DASHBOARD]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER, ALLOW_ROLES.EMPLOYEE],
	[PERMISSIONS.CATEGORIES]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER],
	[PERMISSIONS.ATTRIBUTES]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER],
	[PERMISSIONS.TEMPLATES]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER],
	[PERMISSIONS.PRODUCTS]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER, ALLOW_ROLES.EMPLOYEE],
	[PERMISSIONS.SUPPLIERS]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER],
	[PERMISSIONS.SALES]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER, ALLOW_ROLES.EMPLOYEE],
	[PERMISSIONS.REPORTS]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER],
	[PERMISSIONS.USERS]: [ALLOW_ROLES.ADMIN],
	[PERMISSIONS.CUSTOMERS]: [ALLOW_ROLES.ADMIN, ALLOW_ROLES.MANAGER],
	[PERMISSIONS.ADMINISTRATION]: [ALLOW_ROLES.ADMIN],
}
