export const PATH_SOURCE = {
  AUTH: 'auth',
  FILES: 'file',
  USER: 'user',
  CATEGORY: 'category',
  ATRIBUTE: 'atribute',
  TEMPLATE: 'template',
  TEMPLATE_ATRIBUTE: 'template_atribute',
  SUPPLIER: 'supplier',
  BRAND: 'brand',
  PRODUCT: 'product',
  KARDEX: 'kardex',
  ESTABLISHMENT: 'establishment',
  CUSTOMER: 'customer',
}
