services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - ${DATABASE_PORT}:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass  ${REDIS_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'pass_123@', 'ping']
      interval: 30s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:17.4-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - boilerplate-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  redis_data:
  boilerplate-db:
