import {
	IconAlertCircle,
	IconAlertSquareRounded,
	IconAlertTriangle,
	IconArchive,
	IconArrowLeft,
	IconArrowNarrowLeft,
	IconArrowNarrowRight,
	IconArrowRight,
	IconBarcode,
	IconBarrel,
	IconBell,
	IconBellBolt,
	IconBellCancel,
	IconBellCheck,
	IconBellCog,
	IconBellExclamation,
	IconBellFilled,
	IconBellHeart,
	IconBellMinus,
	IconBellOff,
	IconBellPlus,
	IconBellQuestion,
	IconBellRinging,
	IconBellRinging2Filled,
	IconBellSchool,
	IconBox,
	IconBoxModel2,
	IconBrandAppgallery,
	IconBrandGithub,
	IconBrandGoogle,
	IconBrandMedium,
	IconBrandTwitter,
	IconBug,
	IconBuilding,
	IconCalendar,
	IconCaretLeft,
	IconCaretLeftFilled,
	IconCaretRight,
	IconCaretRightFilled,
	IconChartArcs,
	IconChartArcs3,
	IconChartArea,
	IconChartAreaFilled,
	IconChartAreaLine,
	IconChartAreaLineFilled,
	IconChartArrows,
	IconChartArrowsVertical,
	IconChartBar,
	IconChartBarOff,
	IconChartBarPopular,
	IconChartBubble,
	IconChartBubbleFilled,
	IconChartCandle,
	IconChartCandleFilled,
	IconChartCircles,
	IconChartCohort,
	IconCheck,
	IconChevronDown,
	IconChevronLeft,
	IconChevronRight,
	IconCircle,
	IconCircleCheck,
	IconCircles,
	IconClearAll,
	IconClick,
	IconClipboardCopy,
	IconClipboardData,
	IconCodeDots,
	IconCommand,
	IconCopy,
	IconCreditCard,
	IconDatabase,
	IconDeviceFloppy,
	IconDeviceLaptop,
	IconDots,
	IconDotsCircleHorizontal,
	IconDotsDiagonal,
	IconDotsDiagonal2,
	IconDotsVertical,
	IconDownload,
	IconEdit,
	IconEye,
	IconEyeClosed,
	IconFile,
	IconFileText,
	IconFileTypePdf,
	IconFileTypeXls,
	IconFilter,
	IconFolder,
	IconGrid3x3,
	IconGrid4x4,
	IconGridDots,
	IconHash,
	IconHelpCircle,
	IconHome,
	IconInfoCircle,
	IconInfoSmall,
	IconKey,
	IconLayersSelected,
	IconLayoutDashboard,
	IconLayoutKanban,
	IconLink,
	IconList,
	IconListDetails,
	IconLoader,
	IconLoader2,
	IconLogin,
	IconLogout,
	IconLogout2,
	IconMail,
	IconMinus,
	IconMoneybag,
	IconMoon,
	IconPencilMinus,
	IconPhoto,
	IconPizza,
	IconPlus,
	IconPoint,
	IconRefresh,
	IconRosetteDiscountCheck,
	IconRotate,
	IconRotate2,
	IconRotate360,
	IconRotate3d,
	IconRotateClockwise,
	IconSearch,
	IconServer,
	IconServerOff,
	IconSettings,
	IconSettingsCog,
	IconShield,
	IconShoppingBag,
	IconSlash,
	IconSortAscending,
	IconSortAscendingLetters,
	IconSortDescendingLetters,
	IconSun,
	IconTable,
	IconTag,
	IconTrademark,
	IconTrash,
	IconTruck,
	IconTruckLoading,
	IconUpload,
	IconUser,
	IconUserBitcoin,
	IconUserBolt,
	IconUserCancel,
	IconUserCheck,
	IconUserCircle,
	IconUserCode,
	IconUserCog,
	IconUserDollar,
	IconUserDown,
	IconUserEdit,
	IconUserExclamation,
	IconUserFilled,
	IconUserHeart,
	IconUserHexagon,
	IconUserOff,
	IconUserPause,
	IconUserPin,
	IconUserPlus,
	IconUsers,
	IconUsersGroup,
	IconUsersMinus,
	IconUserX,
	IconX,
	IconZoom,
} from '@tabler/icons-react'

export const Icons = {
	dashboard: IconLayoutDashboard,
	barCode: IconBarcode,
	moneyBag: IconMoneybag,
	key: IconKey,
	link: IconLink,
	circles: IconCircles,
	fileTypePdf: IconFileTypePdf,
	fileTypeXls: IconFileTypeXls,
	file: IconFile,
	rosetteDiscountCheck: IconRosetteDiscountCheck,
	serverOff: IconServerOff,
	logo: IconCommand,
	truck: IconTruck,
	shield: IconShield,
	infoSmall: IconInfoSmall,
	brandMedium: IconBrandMedium,
	grid4x4: IconGrid4x4,
	tag: IconTag,
	trademark: IconTrademark,
	grid3x3: IconGrid3x3,
	gridDots: IconGridDots,
	list: IconList,
	building: IconBuilding,
	hash: IconHash,
	store: IconBrandAppgallery,
	dataBase: IconDatabase,
	server: IconServer,
	login: IconLogin,
	logout: IconLogout,
	logout2: IconLogout2,
	clearAll: IconClearAll,
	chevronDown: IconChevronDown,
	close: IconX,
	product: IconShoppingBag,
	spinnerSimple: IconLoader2,
	spinnerDecored: IconLoader,
	kanban: IconLayoutKanban,
	chevronLeft: IconChevronLeft,
	chevronRight: IconChevronRight,
	trash: IconTrash,
	truckLoading: IconTruckLoading,
	employee: IconUserX,
	post: IconFileText,
	clipboardData: IconClipboardData,
	page: IconFile,
	userPen: IconUserEdit,
	user2: IconUserCircle,
	media: IconPhoto,
	settings: IconSettings,
	billing: IconCreditCard,
	ellipsis: IconDotsVertical,
	add: IconPlus,
	deviceLaptop: IconDeviceLaptop,
	warning: IconAlertTriangle,
	user: IconUser,
	iconArrowLeft: IconArrowLeft,
	arrowRight: IconArrowRight,
	caretRight: IconCaretRight,
	caretLeft: IconCaretLeft,
	caretRightFill: IconCaretRightFilled,
	caretLeftFill: IconCaretLeftFilled,
	arrowNarrowRight: IconArrowNarrowRight,
	arrowNarrowLeft: IconArrowNarrowLeft,
	help: IconHelpCircle,
	pizza: IconPizza,
	sun: IconSun,
	moon: IconMoon,
	laptop: IconDeviceLaptop,
	github: IconBrandGithub,
	twitter: IconBrandTwitter,
	check: IconCheck,
	mail: IconMail,
	google: IconBrandGoogle,
	box: IconBox,
	boxModel2: IconBoxModel2,
	eye: IconEye,
	eyeClosed: IconEyeClosed,
	cash: IconCreditCard,
	receipt: IconFileText,
	inventory: IconBox,
	discount: IconArrowRight,
	customer: IconUserCircle,
	order: IconShoppingBag,
	table: IconTable,
	menu: IconFile,
	payment: IconCreditCard,
	refund: IconArrowRight,
	report: IconFileText,
	shoppingCart: IconShoppingBag,
	cashRegister: IconCreditCard,
	copy: IconCopy,
	layers: IconLayersSelected,
	folder: IconFolder,

	dotsVertical: IconDotsVertical,
	dots: IconDots,
	dotsCircleHorizontal: IconDotsCircleHorizontal,
	dotsDiagonal: IconDotsDiagonal,
	dotsDiagonal2: IconDotsDiagonal2,
	dodeDots: IconCodeDots,
	zoom: IconZoom,
	download: IconDownload,
	calendar: IconCalendar,
	home: IconHome,
	search: IconSearch,
	click: IconClick,
	listDetails: IconListDetails,

	// TABLE
	rotate: IconRotate,
	rotate2: IconRotate2,
	rotate360: IconRotate360,
	rotate3d: IconRotate3d,
	rotateClockwise: IconRotateClockwise,
	edit: IconEdit,
	point: IconPoint,
	archive: IconArchive,
	photo: IconPhoto,
	pencilMinus: IconPencilMinus,
	plus: IconPlus,
	refresh: IconRefresh,
	x: IconX,
	sortAscending: IconSortAscending,
	sortAscendingLetters: IconSortAscendingLetters,
	sortDescendingLetters: IconSortDescendingLetters,
	alertSquareRounded: IconAlertSquareRounded,
	deviceFloppy: IconDeviceFloppy,
	filter: IconFilter,
	alertTriangle: IconAlertTriangle,
	alertCircle: IconAlertCircle,

	// ALERT
	checkCircle: IconCircleCheck,
	infoCircle: IconInfoCircle,
	bug: IconBug,

	upload: IconUpload,
	minus: IconMinus,

	// CHARTS
	chartArcs: IconChartArcs,
	chartArcs3: IconChartArcs3,
	chartArea: IconChartArea,
	chartAreaFilled: IconChartAreaFilled,
	chartAreaLine: IconChartAreaLine,
	chartAreaLineFilled: IconChartAreaLineFilled,
	chartArrows: IconChartArrows,
	chartArrowsVertical: IconChartArrowsVertical,
	chartBar: IconChartBar,
	chartBarOff: IconChartBarOff,
	chartBarPopular: IconChartBarPopular,
	chartBubble: IconChartBubble,
	chartBubbleFilled: IconChartBubbleFilled,
	chartCandle: IconChartCandle,
	chartCandleFilled: IconChartCandleFilled,
	chartCircles: IconChartCircles,
	chartCohort: IconChartCohort,

	settingsCog: IconSettingsCog,
	slash: IconSlash,

	// Iconos de campana (bell)
	bell: IconBell, // Campana básica
	bellBolt: IconBellBolt, // Campana con rayo (notificaciones urgentes)
	bellRinging2Filled: IconBellRinging2Filled, // Campana sonando (relleno)
	bellOff: IconBellOff, // Campana desactivada
	bellPlus: IconBellPlus, // Campana con signo +
	bellMinus: IconBellMinus, // Campana con signo -
	bellQuestion: IconBellQuestion, // Campana con signo ?
	bellExclamation: IconBellExclamation, // Campana con signo !
	bellSchool: IconBellSchool, // Campana de escuela
	bellCancel: IconBellCancel, // Campana con símbolo de cancelación
	bellCheck: IconBellCheck, // Campana con marca de verificación
	bellHeart: IconBellHeart, // Campana con corazón
	bellRinging: IconBellRinging, // Campana sonando (otra variante)
	bellFilled: IconBellFilled, // Campana rellena
	bellCog: IconBellCog, // Campana con icono de configuración

	// USERS
	userX: IconUserX,
	userCog: IconUserCog,
	userOff: IconUserOff,
	userPin: IconUserPin,
	userUsers: IconUsers,
	userBolt: IconUserBolt,
	userEdit: IconUserEdit,
	userCode: IconUserCode,
	userDown: IconUserDown,
	userPlus: IconUserPlus,
	userCheck: IconUserCheck,
	userHeart: IconUserHeart,
	userPause: IconUserPause,
	userGroup: IconUsersGroup,
	userMinus: IconUsersMinus,
	userFilled: IconUserFilled,
	userCircle: IconUserCircle,
	userCancel: IconUserCancel,
	userDollar: IconUserDollar,
	userBitcoin: IconUserBitcoin,
	userHexagon: IconUserHexagon,
	userExclamation: IconUserExclamation,
}
